package com.entity;

import java.util.ArrayList;
import java.util.List;

// default package
// Generated 2013-7-19 16:38:26 by Hibernate Tools 4.0.0

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private int id;
	private String serviceType;
	private Integer serviceId;
	private String startLocation;
	private String destination;
	private String startLocationAddress;
	private String destinationAddress;
	private Double cost;
	private Integer duration;
	private String website;
	private String url;

	private String snsUrl;
	private String postCode;

	protected List<Proposition> prePropositions = new ArrayList<Proposition>();
	protected List<Proposition> positiveEffects = new ArrayList<Proposition>();
	protected List<Proposition> negativeEffects = new ArrayList<Proposition>();

	public Activity() {
	}

	public Activity(int id) {
		this.id = id;
	}

	public Activity(int id, String serviceType, Integer serviceId,
			String startlocation, String destination, String startaddress,
			String destinationaddress, Double cost, Integer duration,
			String website, String url) {
		this.id = id;
		this.serviceType = serviceType;
		this.serviceId = serviceId;
		this.startLocation = startlocation;
		this.destination = destination;
		this.startLocationAddress = startaddress;
		this.destinationAddress = destinationaddress;
		this.cost = cost;
		this.duration = duration;
		this.website = website;
		this.url = url;

	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	public String getStartLocation() {
		return this.startLocation;
	}

	public void setStartLocation(String startlocation) {
		this.startLocation = startlocation;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getStartLocationAddress() {
		return startLocationAddress;
	}

	public void setStartLocationAddress(String startLocationAddress) {
		this.startLocationAddress = startLocationAddress;
	}

	public String getDestinationAddress() {
		return destinationAddress;
	}

	public void setDestinationAddress(String destinationAddress) {
		this.destinationAddress = destinationAddress;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public List<Proposition> getPrePropositions() {
		return prePropositions;
	}

	public void setPrePropositions(List<Proposition> prePropositions) {
		this.prePropositions = prePropositions;
	}

	public List<Proposition> getPositiveEffects() {
		return positiveEffects;
	}

	public void setPositiveEffects(List<Proposition> positiveEffects) {
		this.positiveEffects = positiveEffects;
	}

	public List<Proposition> getNegativeEffects() {
		return negativeEffects;
	}

	public void setNegativeEffects(List<Proposition> negativeEffects) {
		this.negativeEffects = negativeEffects;
	}

	public String getSnsUrl() {
		return snsUrl;
	}

	public void setSnsUrl(String snsUrl) {
		this.snsUrl = snsUrl;
	}

	public String getPostCode() {
		return postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Override
	public String toString() {
		return "Activity [id=" + id + ", serviceType=" + serviceType
				+ ", serviceId=" + serviceId + ", startLocation="
				+ startLocation + ", destination=" + destination
				+ ", startLocationAddress=" + startLocationAddress
				+ ", destinationAddress=" + destinationAddress + ", cost="
				+ cost + ", duration=" + duration + "]";
	}

}
