package com.entity;

// default package
// Generated 2013-7-17 15:44:04 by Hibernate Tools 4.0.0

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private String id;
	private String code;
	private String name;
	private String lat;
	private String lon;
	private String url;
	private String type;

	public Station() {
	}

	public Station(String id) {
		this.id = id;
	}

	public Station(String id, String code, String name, String lat, String lon,
			String url, String type) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.lat = lat;
		this.lon = lon;
		this.url = url;
		this.type = type;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getLon() {
		return this.lon;
	}

	public void setLon(String lon) {
		this.lon = lon;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
//		if (type.equals("metro")) {
//			name = name.substring(8);
//			return "Station [id=" + id + ", name=" + name + "]";
//		}
		return "Station [id=" + id + ", name=" + name + "]";
	}

}
