package com.entplanner.entity;




// default package
// Generated 2013-7-19 16:38:26 by Hibernate Tools 4.0.0

/**
 * MovieService generated by hbm2java
 */
public class MovieService implements java.io.Serializable {

	private Integer id;
	private String serviceName;
	private String startLocation;
	private String destination;
	private String startLocationAddress;
	private String destinationAddress;
	private Integer duration;
	private Double cost;
	private String theater;
	private String movieName;
	private String startTimePoint;
	private String website;
	private String url;
	
	private String snsUrl;
	private String postCode;


	public MovieService() {
	}

	public MovieService(String serviceName) {
		this.serviceName = serviceName;
	}

	public MovieService(String serviceName, String startLocation,
			String destination, String startLocationAddress,
			String destinationAddress, Integer duration, Double cost,
			String theater, String movieName, String startTimePoint,
			String website, String url) {
		this.serviceName = serviceName;
		this.startLocation = startLocation;
		this.destination = destination;
		this.startLocationAddress = startLocationAddress;
		this.destinationAddress = destinationAddress;
		this.duration = duration;
		this.cost = cost;
		this.theater = theater;
		this.movieName = movieName;
		this.startTimePoint = startTimePoint;
		this.website = website;
		this.url = url;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getStartLocation() {
		return this.startLocation;
	}

	public void setStartLocation(String startLocation) {
		this.startLocation = startLocation;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getStartLocationAddress() {
		return this.startLocationAddress;
	}

	public void setStartLocationAddress(String startLocationAddress) {
		this.startLocationAddress = startLocationAddress;
	}

	public String getDestinationAddress() {
		return this.destinationAddress;
	}

	public void setDestinationAddress(String destinationAddress) {
		this.destinationAddress = destinationAddress;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public String getTheater() {
		return this.theater;
	}

	public void setTheater(String theater) {
		this.theater = theater;
	}

	public String getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	public String getStartTimePoint() {
		return this.startTimePoint;
	}

	public void setStartTimePoint(String startTimePoint) {
		this.startTimePoint = startTimePoint;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}



	public String getSnsUrl() {
		return snsUrl;
	}

	public void setSnsUrl(String snsUrl) {
		this.snsUrl = snsUrl;
	}

	public String getPostCode() {
		return postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Override
	public String toString() {
		return "MovieService [serviceName=" + serviceName + ", startLocation="
				+ startLocation + ", destination=" + destination
				+ ", startLocationAddress=" + startLocationAddress
				+ ", destinationAddress=" + destinationAddress + ", duration="
				+ duration + ", cost=" + cost + ", theater=" + theater
				+ ", movieName=" + movieName + ", startTimePoint="
				+ startTimePoint + "]";
	}

}
