package com.entplanner.entity;

// default package
// Generated 2013-7-19 16:38:26 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;



/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

	private Integer id;
	private Station station;
	private String name;
	private Integer duration;
	private String displayDuration;
	private Double cost;
	private String originLocation;
	private String travelMode;

	private List<Activity> activityList = new ArrayList<Activity>();
	
	private MovieService movieService;
	private RestaurantService restaurantService;
	private ShoppingService shoppingService;

	private String areaType;
	private String areaLocation;
	private String areaLocationAddress;
	private Integer radius;

	private Double cost_csp;
	private Double time_csp;
	private Double connect_csp;
	
	private String rating;
	
	private Date start_time;

	private List<String> urls = new ArrayList<String>();
	
	private String json;
	
	public Plan() {
	}



	public String getJson() {
		return json;
	}



	public void setJson(String json) {
		this.json = json;
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public String getOriginLocation() {
		return this.originLocation;
	}

	public void setOriginLocation(String originLocation) {
		this.originLocation = originLocation;
	}



	public String getTravelMode() {
		return travelMode;
	}

	public void setTravelMode(String travelMode) {
		this.travelMode = travelMode;
	}

	

	public List<Activity> getActivityList() {

		return activityList;
	}

	public void setActivityList(List<Activity> activityList) {
		this.activityList = activityList;
	}

	public String getAreaType() {
		return areaType;
	}

	public void setAreaType(String areaType) {
		this.areaType = areaType;
	}

	public String getAreaLocation() {
		return areaLocation;
	}

	public void setAreaLocation(String areaLocation) {
		this.areaLocation = areaLocation;
	}

	public String getAreaLocationAddress() {
		return areaLocationAddress;
	}

	public void setAreaLocationAddress(String areaLocationAddress) {
		this.areaLocationAddress = areaLocationAddress;
	}

	public Integer getRadius() {
		return radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public List<String> getUrls() {
		return urls;
	}

	public void setUrls(List<String> urls) {
		this.urls = urls;
	}

	public Double getCost_csp() {
		return cost_csp;
	}

	public void setCost_csp(Double cost_csp) {
		this.cost_csp = cost_csp;
	}

	public Double getTime_csp() {
		return time_csp;
	}

	public void setTime_csp(Double time_csp) {
		this.time_csp = time_csp;
	}

	public Double getConnect_csp() {
		return connect_csp;
	}

	public void setConnect_csp(Double connect_csp) {
		this.connect_csp = connect_csp;
	}

	
	public Date getStart_time() {
		return start_time;
	}

	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}

	

	public MovieService getMovieService() {
		return movieService;
	}

	public void setMovieService(MovieService movieService) {
		this.movieService = movieService;
	}

	public RestaurantService getRestaurantService() {
		return restaurantService;
	}

	public void setRestaurantService(RestaurantService restaurantService) {
		this.restaurantService = restaurantService;
	}

	public ShoppingService getShoppingService() {
		return shoppingService;
	}

	public void setShoppingService(ShoppingService shoppingService) {
		this.shoppingService = shoppingService;
	}



	public String getRating() {
		return rating;
	}



	public void setRating(String rating) {
		this.rating = rating;
	}



	public String getDisplayDuration() {
		return displayDuration;
	}



	public void setDisplayDuration(String displayDuration) {
		this.displayDuration = displayDuration;
	}




	
	
}
