package com.entplanner.entity;




// default package
// Generated 2013-7-19 16:38:26 by Hibernate Tools 4.0.0

/**
 * RestaurantService generated by hbm2java
 */
public class RestaurantService implements java.io.Serializable {

	private Integer id;
	private String serviceName;
	private String startLocation;
	private String destination;
	private String startLocationAddress;
	private String destinationAddress;
	private Integer duration;
	private Double cost;
	private String types;
	private String referenece;
	private String rating;
	private String priceLevel;
	private String website;
	private String url;
	
	private String snsUrl;
	private String postCode;
	private String telephone;
	private String name;



	public RestaurantService() {
	}

	public RestaurantService(String serviceName) {
		this.serviceName = serviceName;
	}

	public RestaurantService(String serviceName, String startLocation,
			String destination, String startLocationAddress,
			String destinationAddress, Integer duration, Double cost,
			String types, String referenece, String rating, String priceLevel,
			String website, String url) {
		this.serviceName = serviceName;
		this.startLocation = startLocation;
		this.destination = destination;
		this.startLocationAddress = startLocationAddress;
		this.destinationAddress = destinationAddress;
		this.duration = duration;
		this.cost = cost;
		this.types = types;
		this.referenece = referenece;
		this.rating = rating;
		this.priceLevel = priceLevel;
		this.website = website;
		this.url = url;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getStartLocation() {
		return this.startLocation;
	}

	public void setStartLocation(String startLocation) {
		this.startLocation = startLocation;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getStartLocationAddress() {
		return this.startLocationAddress;
	}

	public void setStartLocationAddress(String startLocationAddress) {
		this.startLocationAddress = startLocationAddress;
	}

	public String getDestinationAddress() {
		return this.destinationAddress;
	}

	public void setDestinationAddress(String destinationAddress) {
		this.destinationAddress = destinationAddress;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public String getTypes() {
		return this.types;
	}

	public void setTypes(String types) {
		this.types = types;
	}

	public String getReferenece() {
		return this.referenece;
	}

	public void setReferenece(String referenece) {
		this.referenece = referenece;
	}

	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public String getPriceLevel() {
		return this.priceLevel;
	}

	public void setPriceLevel(String priceLevel) {
		this.priceLevel = priceLevel;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}


	public String getSnsUrl() {
		return snsUrl;
	}

	public void setSnsUrl(String snsUrl) {
		this.snsUrl = snsUrl;
	}

	public String getPostCode() {
		return postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public void setPrice() {
		if (this.priceLevel != null) {
			this.setCost(Double.parseDouble(this.priceLevel) * 10);
		} else {
			this.setCost(10.0);
		}
	}

	public void setTimeCost() {
		if (this.priceLevel != null) {
			this.setDuration(60);
		} else {
			this.setDuration(30);
		}
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "RestaurantService [id=" + id + ", serviceName=" + serviceName
				+ ", startLocation=" + startLocation + ", destination="
				+ destination + ", startLocationAddress="
				+ startLocationAddress + ", destinationAddress="
				+ destinationAddress + ", duration=" + duration + ", cost="
				+ cost + ", types=" + types + ", rating=" + rating
				+ ", priceLevel=" + priceLevel + ", postCode=" + postCode + "]";
	}
	
	
	
}
